### PR TITLE
Remove unused dependencies in grafana-chord-plugin and grafana-sankey-plugin

### PR DESCRIPTION
**Pull request by yuntanghsu**
The PR remove unused dependencies in grafana-chord-plugin and grafana-sankey-plugin in order to remove some security issue bumped be dependabot.

I use [depcheck](https://www.npmjs.com/package/depcheck) to find the useless dependency in our package.json.
The remaining useless dependencies found by depcheck are:
```
Unused dependencies
* @emotion/css
* @grafana/runtime
Unused devDependencies
* css-loader
* emotion
* identity-obj-proxy
* prettier
* sass
* sass-loader
* style-loader
* swc-loader
* ts-node
```
But they are used somewhere in .config folder.

@heanlan @Dhruv-J Do you think we need to rebuild the plugins and update the links in yaml file? I've manually verify that there is no issue on UI.

### CODE REVIEW

**Review by Dhruv-J — APPROVED** [review]
LGTM

**Review by heanlan — APPROVED** [review]
LGTM

**Comment by heanlan** [comment]
> Do you think we need to rebuild the plugins and update the links in yaml file? I've manually verify that there is no issue on UI.

I think we can wait for other more significant changes and make a new release together. If there are no other changes on these two plugins until next Theia release, let's do a minor release for chord-1.0.3 and sankey-1.0.4

**Comment by yuntanghsu** [comment]
> > Do you think we need to rebuild the plugins and update the links in yaml file? I've manually verify that there is no issue on UI.
> 
> I think we can wait for other more significant changes and make a new release together. If there are no other changes on these two plugins until next Theia release, let's do a minor release for chord-1.0.3 and sankey-1.0.4. Let me know if you have different opinions.

Sounds good to me. Thanks!

**Pull request merged**
