### PR TITLE
Remove android library in action to save space storage for e2e test.

### PR DESCRIPTION
**Pull request by yuntanghsu**
Add `sudo rm -rf "/usr/local/lib/android"` to release ~10GB space for e2e test.

before
image

after
image

### CODE REVIEW

**Review by heanlan — APPROVED** [review]
LGTM

I'm just curious about how did we decide to remove android instead of other libraries?

**Comment by yuntanghsu** [comment]
> LGTM
> 
> I'm just curious about how did we decide to remove android instead of other libraries?

Those folders are pre-installed and users usually remove them in runtime to increase storage.
I think we won't use android library and it can provide ~12G space, so I delete it.

However, I think it is just a temporary workaround.
I haven't find the reason why our e2e test used all 41G space. (Our builded image only occupy 7G)

**Review by dreamtalen — APPROVED** [review]
LGTM.
Also noticed this script https://github.com/apache/flink/blob/master/tools/azure-pipelines/free_disk_space.sh Flink is using to free disk spaces. We can try using their commands if we run out of disk space again.

**Review by yanjunz97 — APPROVED** [review]

**Pull request merged**
