### PR TITLE
Upload ClickHouse-Keeper image in Theia.

### PR DESCRIPTION
**Pull request by tushartathgur**
Adding ClickHouse-Keeper image for kind and unit tests and for manifest yamls

### CODE REVIEW

**Comment by elton-furtado** [comment]
let's keep all the clickhouse-keeper in one PR

**Comment by tushartathgur** [comment]
> let's keep all the clickhouse-keeper changes in one PR

we will have to keep this update separate for the test cases to be able to fetch the image from the repository, we will first have to upload the image to the repository.

**Comment by elton-furtado** [comment]
> 

which testcases?  for now we shouldn't be adding any new tests for clickhouse-keeper.

**Comment by tushartathgur** [comment]
> which testcases? for now we shouldn't be adding any new tests for clickhouse-keeper.

in the PR #281, we were using click house-keeper image directly from docker, which instead should be first uploaded to the Theia image repo in harbor and should then be pulled for using in test cases, test cases currently in #281 would fail if the image is not present.

**Pull request closed without merging**
