### PR TITLE
Bump ClickHouse image from 21.11 to 22.6

### PR DESCRIPTION
**Pull request by wsquan171**
Signed-off-by: Shawn Wang <wshaoquan@vmware.com>

### CODE REVIEW

**Review by dreamtalen — APPROVED** [review]
We may also need an update here: https://github.com/antrea-io/theia/blob/main/ci/kind/test-upgrade-theia.sh#L152

**Comment by wsquan171** [comment]
> We may also need an update here: https://github.com/antrea-io/theia/blob/main/ci/kind/test-upgrade-theia.sh#L152

Thanks. updated

**Review by yanjunz97 — APPROVED** [review]

**Comment by yanjunz97** [comment]
I notice many of test failures are caused by the the clickhouse monitor e2e test with the following errors in log
```bash
[clickhouse][connect=5][prepare] SELECT timeInserted FROM default.flows_local LIMIT 1 OFFSET $1
[clickhouse][connect=5][stmt] close
E0831 11:23:42.526267       1 main.go:296] \"Failed to get timeInserted boundary\" err=\"sql: expected 0 arguments, got 1\" table name=\"default.flows_local\"
````
With some tries, I find it seems clickhouse-go v1 does not support `$` as the placeholder. I'm not sure why this test sometimes passed, but maybe we can replace `$1` by `(?)` to resolve this failure.

Here are the changes may need to apply:

https://github.com/antrea-io/theia/blob/79f07a51d73acf02a211435e8ea8fd821a2b28df/plugins/clickhouse-monitor/main.go#L273
To
```
query := fmt.Sprintf("ALTER TABLE %s DELETE WHERE timeInserted < toDateTime(?)", table)
```

https://github.com/antrea-io/theia/blob/79f07a51d73acf02a211435e8ea8fd821a2b28df/plugins/clickhouse-monitor/main.go#L292
To
```
query := fmt.Sprintf("SELECT timeInserted FROM %s LIMIT 1 OFFSET (?)", tableName)
```

https://github.com/antrea-io/theia/blob/79f07a51d73acf02a211435e8ea8fd821a2b28df/plugins/clickhouse-monitor/main_test.go#L65-L67
To
```
mock.ExpectQuery("SELECT timeInserted FROM flows LIMIT 1 OFFSET (?)").WithArgs(4).WillReturnRows(timeRow)
	for _, table := range []string{"flows", "flows_pod_view", "flows_node_view", "flows_policy_view"} {
		query := fmt.Sprintf("ALTER TABLE %s DELETE WHERE timeInserted < toDateTime(?)", table)
```

Do you prefer to include these changes in this PR or let me open another PR to fix this?

**Review by yuntanghsu — APPROVED** [review]

**Pull request merged**
